<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-Q9R4LGA" failures="1" tests="1" name="api.test.CommentTest" time="3.464" errors="0" timestamp="2023-07-17T17:00:11 WIB" skipped="0">
  <testcase classname="api.test.CommentTest" name="CMT001" time="3.464">
    <failure message="{
    &quot;id&quot;: 45932,
    &quot;post_id&quot;: 51937,
    &quot;name&quot;: &quot;Javier Moore IV&quot;,
    &quot;email&quot;: &quot;filiberto.haley@gmail.com&quot;,
    &quot;body&quot;: &quot;Atque facilis qui fugiat iste voluptates et.&quot;
}" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: {
    "id": 45932,
    "post_id": 51937,
    "name": "Javier Moore IV",
    "email": "filiberto.haley@gmail.com",
    "body": "Atque facilis qui fugiat iste voluptates et."
}
at org.testng.Assert.fail(Assert.java:110)
at api.test.CommentTest.CMT001(CommentTest.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CMT001 -->
  <system-out/>
</testsuite> <!-- api.test.CommentTest -->
